# Generated by Django 4.2.17 on 2025-02-02 16:28
from ..initial_data import populate_groups
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20250114_1030'),
    ]

    operations = [migrations.RunPython(populate_groups)
    ]
