# Generated by Django 4.2.17 on 2025-03-15 14:27
from ..initial_data import populate_groups
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_alter_blogpost_image'),
    ]

    operations = [migrations.RunPython(populate_groups)
    ]
