# Generated by Django 4.2.17 on 2025-03-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20250315_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='https://djangoblog-bucket.blr1.cdn.digitaloceanspaces.com/default/Default_pfp.jpg', null=True, upload_to='profile-pictures/'),
        ),
    ]
